# Generated by Django 5.0.6 on 2025-02-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliate_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('registered', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='affiliates.affiliate')),
            ],
        ),
    ]
