# Generated by Django 5.0.6 on 2025-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='workout_video',
            field=models.FileField(blank=True, null=True, upload_to='coaches_videos/'),
        ),
    ]
