# Generated by Django 5.0.6 on 2025-01-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='resume',
            field=models.FileField(blank=True, help_text='Required for Nutritionists', null=True, upload_to='nutritionist_resumes/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='coach',
            name='specialization',
            field=models.CharField(choices=[('Personal Trainer', 'Personal Trainer'), ('Yoga Instructor', 'Yoga Instructor'), ('Nutritionist', 'Nutritionist'), ('Strength Coach', 'Strength Coach')], max_length=50),
        ),
    ]
