# Generated by Django 5.0.6 on 2025-02-19 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_commission_paid_order_referrer_affiliate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral',
            new_name='Lead',
        ),
        migrations.RenameModel(
            old_name='Affiliate',
            new_name='Marketer',
        ),
    ]
