# Generated by Django 5.0.6 on 2025-02-19 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_referral_lead_rename_affiliate_marketer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketer',
            new_name='Affiliate',
        ),
        migrations.RenameModel(
            old_name='Lead',
            new_name='Referral',
        ),
    ]
