# Generated by Django 5.0.6 on 2025-02-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_marketer_affiliate_rename_lead_referral'),
    ]

    operations = [
    ]
