# Generated by Django 5.0.6 on 2025-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20250219_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='commission_rate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
