# Generated by Django 5.0.6 on 2025-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_affiliate_commission_rate_affiliate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
