# Generated by Django 5.0.6 on 2025-02-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_affiliate_status'),
    ]

    operations = [
    ]
