# Generated by Django 5.0.6 on 2025-02-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20250221_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_user',
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
