# Generated by Django 5.0.6 on 2025-03-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_alter_referral_referral_code'),
        ('shop', '0010_remove_referral_referrer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='referrer',
        ),
        migrations.AddField(
            model_name='order',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliates.referral'),
        ),
    ]
