# Generated by Django 5.0.6 on 2025-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('CrossFit', 'CrossFit'), ('Personal Trainer', 'Personal Trainer'), ('Nutritionist', 'Nutritionist')], default='Yoga', max_length=50),
        ),
    ]
