# Generated by Django 5.0.6 on 2025-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
