# Generated by Django 5.0.6 on 2025-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_contactsubmission_admin_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='enquiry_type',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('complaint', 'Complaint'), ('pricing', 'Pricing'), ('membership', 'Membership'), ('other', 'Other'), ('feedback', 'Feedback')], default='enquiry', max_length=20),
        ),
    ]
