# Generated by Django 5.0.6 on 2025-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_contactsubmission_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
