# Generated by Django 5.0.6 on 2025-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_contactsubmission_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
