# Generated by Django 5.0.6 on 2025-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_contactsubmission_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
