# Generated by Django 5.0.6 on 2025-01-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_coach_resume_alter_coach_hourly_rate_and_more'),
        ('gym', '0004_service_category'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.coach')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.service')),
            ],
        ),
    ]
